export const projectImages = [
  { id: 'metro', title: 'Metrô', path: 'imgs/fotometro.jpeg' },
  { id: 'porto', title: 'Portos', path: 'imgs/fotoportos.jpeg' },
  { id: 'aeroporto', title: 'Aeroportos', path: 'imgs/fotoaeroporto.jpeg' },
  { id: 'barragem', title: 'Barragens', path: 'imgs/fotobarragem.jpeg' },
  { id: 'construcao', title: 'Construção Industrial/Civil', path: 'imgs/fotoconstrucao.jpeg' },
  { id: 'dique', title: 'Dique Seco', path: 'imgs/fotodique.jpeg' },
  { id: 'rodovia', title: 'Rodovias', path: 'imgs/fotorodovia.jpeg' },
  { id: 'hidreletrica', title: 'Hidrelétricas', path: 'imgs/fotohidreletrica.jpeg' },
  { id: 'tunel', title: 'Túneis', path: 'imgs/fototunel.jpeg' },
  { id: 'adutora', title: 'Adutoras', path: 'imgs/fotoadutora.jpeg' },
  { id: 'eta', title: 'Estação de Tratamento de Água', path: 'imgs/fotoeta.jpeg' },
  { id: 'ete', title: 'Estação de Tratamento de Esgotos', path: 'imgs/fotoete.jpeg' },
  { id: 'redes', title: 'Interceptores e Redes Domiciliares de Esgoto', path: 'imgs/fotoredes.jpeg' },
  { id: 'termoeletrica', title: 'Termoelétrica', path: 'imgs/fototermoeletrica.jpeg' },
  { id: 'cimento', title: 'Fábrica de Cimento', path: 'imgs/fotocimento.jpeg' },
];
