export const projectImages = [
  { id: 'metro', title: 'Metrô', path: '/imgs/fotoMetro.jpeg' },
  { id: 'porto', title: 'Portos', path: '/imgs/FotoPortos.jpeg' },
  { id: 'aeroporto', title: 'Aeroportos', path: '/imgs/FotoAeroporto.jpeg' },
  { id: 'barragem', title: 'Barragens', path: '/imgs/fotoBarragem.jpeg' },
  { id: 'construcao', title: 'Construção Industrial/Civil', path: '/imgs/fotoConstrucao.jpeg' },
  { id: 'dique', title: 'Dique Seco', path: '/imgs/fotoDique.jpeg' },
  { id: 'rodovia', title: 'Rodovias', path: '/imgs/fotoRodovia.jpeg' },
  { id: 'hidreletrica', title: 'Hidrelétricas', path: '/imgs/fotoHidreletrica.jpeg' },
  { id: 'tunel', title: 'Túneis', path: '/imgs/fotoTunel.jpeg' },
  { id: 'adutora', title: 'Adutoras', path: '/imgs/fotoAdutora.jpeg' },
  { id: 'eta', title: 'Estação de Tratamento de Água', path: '/imgs/fotoETA.jpeg' },
  { id: 'ete', title: 'Estação de Tratamento de Esgotos', path: '/imgs/fotoETE.jpeg' },
  { id: 'redes', title: 'Interceptores e Redes Domiciliares de Esgoto', path: '/imgs/fotoRedes.jpeg' },
  { id: 'termoeletrica', title: 'Termoelétrica', path: '/imgs/fotoTermoeletrica.jpeg' },
  { id: 'cimento', title: 'Fábrica de Cimento', path: '/imgs/fotoCimento.jpeg' },
];
