export const projectImages = [
  { id: 'metro', title: 'Metrô', path: '/public/imgs/fotometro.jpeg' },
  { id: 'porto', title: 'Portos', path: '/public/imgs/fotoportos.jpeg' },
  { id: 'aeroporto', title: 'Aeroportos', path: '/public/imgs/fotoaeroporto.jpeg' },
  { id: 'barragem', title: 'Barragens', path: '/public/imgs/fotobarragem.jpeg' },
  { id: 'construcao', title: 'Construção Industrial/Civil', path: '/public/imgs/fotoconstrucao.jpeg' },
  { id: 'dique', title: 'Dique Seco', path: '/public/imgs/FotoDique.jpeg' },
  { id: 'rodovia', title: 'Rodovias', path: '/public/imgs/FotoRodovia.jpeg' },
  { id: 'hidreletrica', title: 'Hidrelétricas', path: '/public/imgs/FotoHidreletrica.jpeg' },
  { id: 'tunel', title: 'Túneis', path: '/public/imgs/FotoTunel.jpeg' },
  { id: 'adutora', title: 'Adutoras', path: '/public/imgs/fotoadutora.jpeg' },
  { id: 'eta', title: 'Estação de Tratamento de Água', path: '/public/imgs/FotoETA.jpeg' },
  { id: 'ete', title: 'Estação de Tratamento de Esgotos', path: '/public/imgs/FotoETE.jpeg' },
  { id: 'redes', title: 'Interceptores e Redes Domiciliares de Esgoto', path: '/public/imgs/FotoRedes.jpeg' },
  { id: 'termoeletrica', title: 'Termoelétrica', path: '/public/imgs/FotoTermoeletrica.jpeg' },
  { id: 'cimento', title: 'Fábrica de Cimento', path: '/public/imgs/FotoCimento.jpeg' },
];
